server.port: ${SERVICE_PORT:8090}

spring:
   application:
      name: ${application.name}
   main:
      allow-bean-definition-overriding: true
   output:
      ansi:
         enabled: always
   profiles:
      include: ${zipkin-profile}
   mvc:
      static-path-pattern: /static/**

dubbo:
    scan:
        basePackages: my.demo.web
    application: # see com.alibaba.dubbo.config.ApplicationConfig
        id: ${application.name}
        name: ${application.name}
        qosEnable: false
    registry: # see com.alibaba.dubbo.config.RegistryConfig
        address: nacos://${nacos.address}
    protocol: # see com.alibaba.dubbo.config.ProtocolConfig
        id: dubbo
        name: dubbo
        host: ${SERVICE_HOST:localhost} # Use POD IP to register Dubbo service
    consumer:
        filter: ${dubbo.filter}

seata:
  enabled: ${seata-enabled}
  application-id: ${application.name}
  tx-service-group: my_demo_gtx
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: ${nacos.address}
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr: ${nacos.address}
      namespace:

nacos.config.server-addr: ${nacos.address}

mydemo:
  version: ${SHOP_VERSION:latest}
  hostname: ${HOSTNAME:localhost}