server.port: 8090

spring:
   application:
      name: ${application.name}
   main:
      allow-bean-definition-overriding: true # dubbo-spring-boot-starter 0.2.1.RELEASE的bug，如果不允许覆盖会报错
   output:
      ansi:
         enabled: always
   profiles:
      active: ${activatedProperties}
   mvc:
      static-path-pattern: /static/**

dubbo:
    scan:
        basePackages: my.demo.test
    application: # see com.alibaba.dubbo.config.ApplicationConfig
        id: ${application.name}
        name: ${application.name}
        qosEnable: false
    registry: # see com.alibaba.dubbo.config.RegistryConfig
        address: ${dubbo.registry}
    consumer:
        filter: ${dubbo.filter}

nacos.config.server-addr: 127.0.0.1:8848