spring:
   zipkin: 
      base-url: ${zipkin.base-url}  
      sleuth:
         sampler:
            percentage: 1.0  # 1.0 stands for 100%

zipkin:
   server: ${zipkin.base-url}/api/v2/spans
   connectTimeout: 5000
   readTimeout: 5000