server.port: 8090

spring:
   application:
      name: ${application.name}
   main:
      allow-bean-definition-overriding: true # dubbo-spring-boot-starter 0.2.1.RELEASE的bug，如果不允许覆盖会报错
   output:
      ansi:
         enabled: always
   profiles:
      active: ${activatedProperties}
   mvc:
      static-path-pattern: /static/**

dubbo:
    scan:
        basePackages: my.demo.test
    application: # see com.alibaba.dubbo.config.ApplicationConfig
        id: ${application.name}
        name: ${application.name}
        qosEnable: false
    registry: # see com.alibaba.dubbo.config.RegistryConfig
        address: ${dubbo.registry}
    consumer:
        filter: ${dubbo.filter}

nacos.config.server-addr: 127.0.0.1:8848

seata:
  enabled: true
  application-id: ${application.name}
  tx-service-group: my_demo_gtx
  client:
    rm-async-commit-buffer-limit: 1000
    rm-report-retry-count: 5
    rm-table-meta-check-enable: false
    rm-report-success-enable: true
    rm:
      lock:
        lock-retry-interval: 10
        lock-retry-times: 30
        lock-retry-policy-branch-rollback-on-conflict: true
    tm-commit-retry-count: 5
    tm-rollback-retry-count: 5
    support:
      spring:
        datasource-autoproxy: true
    undo:
      undo-data-validation: true
      undo-log-serialization: jackson
      undo-log-table: undo_log
    client:
      log:
        exceptionRate: 100
  service:
    vgroup-mapping: default
    grouplist: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 192.168.31.108:8848
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr: 192.168.31.108:8848
      namespace: