schemaName: db_order
dataSources: #数据源配置，可配置多个
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/mydemo-dn1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    connectionTimeoutMilliseconds: 3000 #连接超时毫秒数
    idleTimeoutMilliseconds: 60000 #空闲连接回收超时毫秒数
    maxLifetimeMilliseconds: 1800000 #连接最大存活时间毫秒数
    maxPoolSize: 3
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/mydemo-dn2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 3
  ds_2:
    url: jdbc:mysql://127.0.0.1:3306/mydemo-dn3?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 3
  ds_3:
    url: jdbc:mysql://127.0.0.1:3306/mydemo-dn4?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 3
shardingRule:
  tables:
    ord_order:
      actualDataNodes: ds_${0..3}.ord_order
      databaseStrategy:
        inline: 
          shardingColumn: order_id
          algorithmExpression: ds_${order_id % 4}
    ord_order_item:
      actualDataNodes: ds_${0..3}.ord_order_item
      databaseStrategy:
        inline: 
          shardingColumn: order_id
          algorithmExpression: ds_${order_id % 4}
      keyGenerator:
        type: SNOWFLAKE
        column: order_item_id
        props: 
          worker.id: 1
          max.tolerate.time.difference.milliseconds: 600000 # 允许的系统时钟回拨10分钟
    ord_user_order:
      actualDataNodes: ds_${0..3}.ord_user_order
      databaseStrategy:
        inline: 
          shardingColumn: user_id
          algorithmExpression: ds_${user_id % 17 % 4}
    undo_log:
        actualDataNodes: ds_0.undo_log
  bindingTables:
    - ord_order,ord_order_item
  defaultDataSourceName: ds_0
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none: