#orchestration:
#  name: orchestration_ds
#  overwrite: true
#  registry:
#    type: zookeeper
#    serverLists: 192.168.31.108:2181
#    namespace: orchestration
authentication:
  users: # Account for connecting to ShardingProxy
    root: # root user without authorizedSchemas specified can access all logical schemas
      password: 123
    mydemo: # mydemo user
      password: mydemo
      authorizedSchemas: db_user, db_order
props:
  acceptor.size: 4  # Number of workers for client connections
  proxy.transaction.type: LOCAL
  sql.show: true
