#orchestration:
#  name: orchestration_ds
#  overwrite: true
#  registry:
#    type: zookeeper
#    serverLists: 192.168.31.108:2181
#    namespace: orchestration
authentication:
  users: # 定义逻辑库用户密码
    root: # 用户名：root，可访问所有逻辑库
      password: 123
    mydemo: # 用户名：mydemo
      password: mydemo
      authorizedSchemas: db_user, db_order # 只能访问指定的逻辑库
props:
  acceptor.size: 16  # 接收客户端请求的工作线程数，默认CPU核数*2
  proxy.transaction.type: LOCAL
  sql.show: true
