apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mydemo
spec: # ReplicaSet定义
  replicas: 1
  selector:
    matchLabels:
      svc: db-mydemo
  template: # Pod元数据
    metadata:
      labels:
        tier: mysql
        app: mydemo
        svc: db-mydemo
    spec: # Container定义
      containers:
      - name: db-mydemo
        image: mydemo/mysql:5.7.18
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123"
        ports:
        - containerPort: 3306

---
kind: Service
apiVersion: v1
metadata:
  labels:
    svc: db-mydemo
  name: db-mydemo
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30006
  selector:
    svc: db-mydemo