kind: Service
apiVersion: v1
metadata:
  name: pub-nacos
spec:
  type: NodePort        # Expose service port to host machine
  ports:
  - port: 8848
    targetPort: 8848
    nodePort: 30048     # Expose service port to host machine
  selector:
    svc: pub-nacos
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pub-nacos
spec:
  replicas: 1
  serviceName: pub-nacos
  selector:
    matchLabels:
      svc: pub-nacos
  template:
    metadata:
      labels:
        tier: middleware
        scope: public
        svc: pub-nacos
    spec:
      containers:
      - name: pub-nacos
        image: mydemo/nacos:1.1.4
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "db-mydemo"
        ports:
        - containerPort: 8848
        readinessProbe: # Check whether Nacos is ready
          httpGet:      # Wait until HTTP status ok
            path: /nacos
            port: 8848
          initialDelaySeconds: 3    # Wait initialDelaySeconds to check the first time
          periodSeconds: 5          # Wait periodSeconds to check next time
          timeoutSeconds: 2         # Timeout for check process
      initContainers:
      - name: wait-dependencies
        image: busybox
        imagePullPolicy: IfNotPresent
        # nslookup success until db-mydemo is ready
        # 等待时间可能会比较长：
        # 1. 需要等待依赖项的容器启动，POD进入就绪状态；
        # 2. 需要等待依赖项服务在K8S集群内生效，包括DNS解析在本容器中生效；
        command: ['sh', '-c', 'until nslookup db-mydemo; do echo "Waiting for db-mydemo"; sleep 3; done;']