apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-user
spec:
  replicas: 2
  selector:
    matchLabels:
      svc: svc-user
  template:
    metadata:
      labels:
        tier: dubbo
        scope: mydemo
        svc: svc-user
    spec:
      containers:
      - name: svc-user
        image: mydemo/user
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "mycat-mydemo"
        - name: NACOS_HOST
          value: "pub-nacos"
        - name: ZIPKIN_HOST
          value: "pub-zipkin"
        - name: SERVICE_HOST # Use POD IP to register Dubbo service
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_PORT
          value: "20880"
        ports:
        - containerPort: 20880
        readinessProbe:  # Check whether User Service is ready
          #tcpSocket:    # Wait until TCP port is opened
          #  port: 20880
          # 使用tcpSocket方式，k8s会不断与20880端口建立、断开连接，导致Dubbo不断打印"[DUBBO] disconnected from /10.1.0.1:33994 ..."日志，所以这里改用exec方式
          exec:
            command: ["sh", "-c", "COUNT=`netstat -antp tcp | grep 20880 | grep LISTEN -c`; if [ $COUNT -eq 1 ]; then exit 0; else exit 1; fi"]
          initialDelaySeconds: 3    # Wait initialDelaySeconds to check the first time
          periodSeconds: 5          # Wait periodSeconds to check next time
          timeoutSeconds: 1         # Timeout for check process
      initContainers:
      - name: wait-dependencies
        image: busybox
        imagePullPolicy: IfNotPresent
        # 等待时间可能会比较长：
        # 1. 需要等待依赖项的容器启动，POD进入就绪状态；
        # 2. 需要等待依赖项服务在K8S集群内生效，包括DNS解析在本容器中生效；
        command: ['sh', '-c', 'until nslookup mycat-mydemo; do echo "Waiting for mycat-mydemo"; sleep 3; done; until nslookup pub-nacos; do echo "Waiting for pub-nacos"; sleep 3; done;']