apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-user
spec: # ReplicaSet定义
  replicas: 2
  selector:
    matchLabels:
      svc: svc-user
  template: # Pod元数据
    metadata:
      labels:
        tier: dubbo
        svc: svc-user
    spec: # Container定义
      containers:
      - name: svc-user
        image: mydemo/user
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "mycat-mydemo"
        - name: NACOS_HOST
          value: "com-nacos"
        - name: ZIPKIN_HOST
          value: "com-zipkin"
        - name: SERVICE_HOST # 使用POD IP注册Dubbo服务
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_PORT
          value: "20880"
        ports:
        - containerPort: 20880