apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-order
spec: # ReplicaSet定义
  replicas: 1
  selector:
    matchLabels:
      svc: svc-order
  template: # Pod元数据
    metadata:
      labels:
        tier: dubbo
        svc: svc-order
    spec: # Container定义
      containers:
      - name: svc-order
        image: mydemo/order
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "mycat-mydemo"
        - name: NACOS_HOST
          value: "com-nacos"
        - name: ZIPKIN_HOST
          value: "com-zipkin"
        - name: SERVICE_HOST # 使用POD IP注册Dubbo服务
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_PORT
          value: "20880"
        ports:
        - containerPort: 20880