kind: Service
apiVersion: v1
metadata:
  name: web-shopweb
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
  selector:
    svc: web-shopweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-shopweb
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: web-shopweb
  template:
    metadata:
      labels:
        tier: web
        scope: mydemo
        svc: web-shopweb
    spec:
      containers:
      - name: web-shopweb
        image: mydemo/shopweb
        imagePullPolicy: IfNotPresent
        env:
        - name: NACOS_HOST
          value: "pub-nacos"
        - name: ZIPKIN_HOST
          value: "pub-zipkin"
        ports:
        - containerPort: 8090
        readinessProbe: # Check whether shopweb is ready
          httpGet:      # Wait until HTTP status ok
            path: /shop
            port: 8090
          initialDelaySeconds: 3    # Wait initialDelaySeconds to check the first time
          periodSeconds: 5          # Wait periodSeconds to check next time
          timeoutSeconds: 2         # Timeout for check process
      initContainers:
      - name: wait-dependencies
        image: busybox
        imagePullPolicy: IfNotPresent
        # 等待时间可能会比较长：
        # 1. 需要等待依赖项的容器启动，POD进入就绪状态；
        # 2. 需要等待依赖项服务在K8S集群内生效，包括DNS解析在本容器中生效；
        command: ['sh', '-c', 'until nslookup pub-nacos; do echo "Waiting for pub-nacos"; sleep 3; done;']