spring:
   main:
      allow-bean-definition-overriding: true
   output:
      ansi:
         enabled: always

dubbo:
    application: # see com.alibaba.dubbo.config.ApplicationConfig
        id: ${application.name}-srv
        name: ${application.name}-srv
        qosEnable: false
    protocol: # see com.alibaba.dubbo.config.ProtocolConfig
        id: dubbo
        name: dubbo
        host: ${SERVICE_HOST:localhost} # Use POD IP to register Dubbo service
        port: ${SERVICE_PORT:20880}
        threads: 3
        iothreads: 1
        server: netty
        client: netty
        status: server
        serialization: fst
        queues: 0
        keepAlive: true
    registry: # see com.alibaba.dubbo.config.RegistryConfig
        address: nacos://${nacos.address}
        check: false
    provider:
        cluster: failfast
        retries: 0
        loadbalance: roundrobin
        timeout: 10000
        filter: ${dubbo.filter}

zipkin:
   server: ${zipkin.base-url}/api/v2/spans
   connectTimeout: 5000
   readTimeout: 5000